### ISSUE TITLE
Spec typo: `ethiopicaa` should be `ethioaa`

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-intl-era-monthcode#17]
The spec lists a calendar with ID `ethiopicaa` but the actual calendar ID is `ethioaa`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getCalendars#ethioaa

**Comment by FrankYFTang** [comment]
fixed by https://github.com/tc39/proposal-intl-era-monthcode/pull/19
